# 101 NumPy Exercises for Data Analysis (Python)

### Link: [Click Here](https://www.machinelearningplus.com/101-numpy-exercises-python/)


### 1. Import numpy as np and see the version

In [1]:
import numpy as np
print(np.__version__)

1.14.0


### 2. How to create a 1D array?

In [2]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. How to create a boolean array?

In [3]:
arr=np.full((3,3),True,dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to extract items that satisfy a given condition from 1D array?

In [4]:
arr=np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

### 5. How to replace items that satisfy a condition with another value in numpy array?

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 6. How to replace items that satisfy a condition without affecting the original array?

In [7]:
arr=np.arange(10)
out=np.where(arr%2==1,-1,arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 7. How to reshape an array?

In [8]:
arr=np.arange(10)
arr=arr.reshape(2,-1)  # set -1 to automatically determine the cols
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. How to stack two arrays vertically?

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. How to stack two arrays horizontally?

In [12]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

In [13]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?

In [14]:
#Desire Output> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a=np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [15]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [16]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 11. How to get the common items between two python numpy arrays?

In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [19]:
np.intersect1d(a,b)

array([2, 4])

### 12. How to remove from one array those items that exist in another?

In [20]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?

In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. How to extract all numbers between a given range from a numpy array?

In [22]:
a = np.arange(15)

In [23]:
desire=np.array([ 5,  6,  7,  8,  9, 10])

In [24]:
a[(a>=5) & (a<=10)]

array([ 5,  6,  7,  8,  9, 10])

### 15. How to make a python function that handles scalars to work on numpy arrays?

In [25]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#pair_max > array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [28]:
def maxx(a,b):
    if a>b:
        return a
    else:
        return b
pair_max=np.vectorize(maxx,otypes=[float])

In [29]:
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

### 16. How to swap two columns in a 2d numpy array?

In [30]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 17. How to swap two rows in a 2d numpy array?

In [33]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### 18. How to reverse the rows of a 2D array?

In [35]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 19. How to reverse the columns of a 2D array?

In [37]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 20. How to create a 2D array containing random floats between 5 and 10?

In [38]:
rand_unif=np.random.uniform(5,10,size=(5,3))
rand_unif

array([[7.85778381, 5.20662252, 7.07430568],
       [6.33506985, 8.48184918, 7.5392331 ],
       [9.93072749, 6.53823928, 8.63929379],
       [6.44441999, 7.29444138, 6.38727446],
       [6.80579307, 6.71924503, 6.40922814]])

### 21. How to print only 3 decimal places in python numpy array?

In [39]:
np.random.random([5,3])

array([[0.6735879 , 0.41669928, 0.12876105],
       [0.40702621, 0.94287552, 0.25630058],
       [0.73695705, 0.19059564, 0.17612937],
       [0.90309626, 0.1655635 , 0.12501896],
       [0.82867522, 0.44842265, 0.31369654]])

### 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [40]:
np.random.random([3,3])/1e3

array([[6.96446436e-04, 2.95819521e-06, 5.82131338e-04],
       [2.05796992e-04, 3.26387287e-04, 4.56614819e-04],
       [7.01856782e-04, 4.82281041e-05, 9.74985331e-04]])

### 23. How to limit the number of items printed in output of numpy array?

In [41]:
np.set_printoptions(threshold=6)
np.arange(15)

array([ 0,  1,  2, ..., 12, 13, 14])

### 24. How to print the full numpy array without truncating

In [42]:
np.set_printoptions(threshold=np.nan)
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [43]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [44]:
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

### 26. How to extract a particular column from 1D array of tuples?

In [45]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

(150,)


D:\Programs\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


In [46]:
species = np.array([row[4] for row in iris_1d])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')