# 101 NumPy Exercises for Data Analysis (Python)

### Link: [Click Here](https://www.machinelearningplus.com/101-numpy-exercises-python/)


### 1. Import numpy as np and see the version

In [1]:
import numpy as np
print(np.__version__)

1.14.0


### 2. How to create a 1D array?

In [2]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. How to create a boolean array?

In [3]:
arr=np.full((3,3),True,dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to extract items that satisfy a given condition from 1D array?

In [4]:
arr=np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

### 5. How to replace items that satisfy a condition with another value in numpy array?

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 6. How to replace items that satisfy a condition without affecting the original array?

In [7]:
arr=np.arange(10)
out=np.where(arr%2==1,-1,arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 7. How to reshape an array?

In [8]:
arr=np.arange(10)
arr=arr.reshape(2,-1)  # set -1 to automatically determine the cols
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. How to stack two arrays vertically?

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. How to stack two arrays horizontally?

In [12]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

In [13]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?

In [14]:
#Desire Output> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a=np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [15]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [16]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 11. How to get the common items between two python numpy arrays?

In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [19]:
np.intersect1d(a,b)

array([2, 4])

### 12. How to remove from one array those items that exist in another?

In [20]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?

In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. How to extract all numbers between a given range from a numpy array?

In [22]:
a = np.arange(15)

In [23]:
desire=np.array([ 5,  6,  7,  8,  9, 10])

In [24]:
a[(a>=5) & (a<=10)]

array([ 5,  6,  7,  8,  9, 10])

### 15. How to make a python function that handles scalars to work on numpy arrays?

In [25]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#pair_max > array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [28]:
def maxx(a,b):
    if a>b:
        return a
    else:
        return b
pair_max=np.vectorize(maxx,otypes=[float])

In [29]:
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

### 16. How to swap two columns in a 2d numpy array?